### ISSUE TITLE
Homey Pro Early 2023?

### ISSUE THREAD

**Issue by magnil2** [emilohman/homey-nibe#21]
Hi!, Will you update the app to work with Homey Pro Early 2023?

**Comment by andreas-bergstrom** [comment]
What would be needed to support this? Any help needed?

**Comment by emilohman** [comment]
Good reminder, thanks! The app needs to be updated to sdk v3: 

https://apps.developer.homey.app/upgrade-guides/upgrading-to-sdk-v3

**Comment by Steeg901** [comment]
Hello, do you want to build it also for vaillant? https://developer.vaillant-group.com/

**Comment by emilohman** [comment]
@Steeg901  Sorry but I don't have one so that will be hard.

**Comment by emilohman** [comment]
Have upgraded to sdk 3 now, so it should work with Homey Pro Early 2023.

**Comment by magnil2** [comment]
Great work, thank you!
