### ISSUE TITLE
Phase 1 and 3 switched

### ISSUE THREAD

**Issue by Krisstenswe** [emilohman/homey-nibe#22]
Hi Emil!
Thanks for a great app!
I have discovered a possible bug - phase 1 and 3 are switched.
I have Tibbers Pulse P1. In both the Tibber app and the Nibe Uplink app, the phases correlate with each other, but in the Homey app as well as Insights, phase 1 and 3 are switched.

**Comment by emilohman** [comment]
Thanks! Will fix that in the next release. Can't promise when.

**Comment by emilohman** [comment]
Should be fixed now.

**Comment by Krisstenswe** [comment]
Seems to be working nice! Thnx!

 

Best regards,

/Kristofer

 

Från: Emil Öhman ***@***.*** 
Skickat: den 9 januari 2023 21:13
Till: emilohman/homey-nibe ***@***.***>
Kopia: Krisstenswe ***@***.***>; Author ***@***.***>
Ämne: Re: [emilohman/homey-nibe] Phase 1 and 3 switched (Issue #22)

 

Should be fixed now.
