### ISSUE TITLE
"403 Forbidden" Can not control settings despite Premium account

### ISSUE THREAD

**Issue by Akersro** [emilohman/homey-nibe#7]
When I try to set "Hot water boost" or "Ventilation boost" it does not work and I get the error message "403 Forbidden". The error message is a pop-up message within the Homey App when I controlI Nibe directly in "Devices". When i try to control it in a flow I gett the Error triangle when running a test, and I can confirm in my Nibe system that the command has not reached through. 

I have a Nibe F370 and just connected it with Uplink. I signed up for a Premium account and it do work to control Hot water boost from the NIBE Uplink App. I have updated my Nibe F370 with the latest SW.

I hope you can figure out what is wrong and that NIBE has not made a change to prevent control. My purpose is to be able to demand Hot water boost when my solarpanels are charging.

**Comment by emilohman** [comment]
Do you still have this problem? I will digg into this when I have some more time.

**Comment by Akersro** [comment]
Hi Emil

Yes, still same problem. If it helps you, I can tell you my Nibe account details so you can log in and see for yourself. 

Thomas

**Comment by emilohman** [comment]
If you are ok with that please email them to me emilohman@gmail.com and I will try to fix it.

**Comment by emilohman** [comment]
The fix has just been published. Please try it out!

**Comment by Akersro** [comment]
Thanks Emil,

It seems to work now. Well done, thanks!!

Thomas
